name: Front-End CI

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: front-end

  unit-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: front-end

      - name: Run unit tests
        run: npm run test:unit
        working-directory: front-end

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: front-end

      - name: Build the application
        run: npm run build
        working-directory: front-end

  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build
    # container:
    #   image: mcr.microsoft.com/playwright:v1.45.0-jammy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: front-end

      - name: Install playwright browsers
        run: npx playwright install --with-deps
        working-directory: front-end

      - name: Run tests
        # timeout-minutes: 10
        run: |
          echo 'ls -l'
          echo 'npm run dev &'
          echo 'sleep 5'
          npm run test:e2e
        working-directory: front-end

  docker:
    runs-on: ubuntu-latest
    needs: [build, unit-tests, e2e-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest
